[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

monitor_speed = 115200

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DUSE_OLED=1
    -DUSE_IMU=1
    -DUSE_ESPNOW=1
    -DFW_VERSION=\"v0.1.14\"

lib_deps =
    adafruit/Adafruit MPU6050 @ ^2.2.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    adafruit/Adafruit SSD1306 @ ^2.5.10
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit BusIO @ ^1.14.5
    h2zero/NimBLE-Arduino @ ^1.4.2
