[env:m5stick-c-plus]
platform = espressif32
board = m5stick-c
framework = arduino

monitor_speed = 115200
upload_speed = 1500000

build_flags =
    -DFW_VERSION='"v0.0.1"'
    -DCONFIG_BT_NIMBLE_ENABLED=1

lib_deps =
    m5stack/M5StickCPlus @ ^0.0.9
    h2zero/NimBLE-Arduino @ ^1.4.2
